openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /version:
    get:
      summary: Get the version string of the implementation.
      responses:
        '200':
          description: version string
          content:
            application/json:
              schema:
                type: string

  /similarity:
    summary: Calculates the spectral similarity between the query peak list and the reference spectra list.
    post:
      summary: Create a new similarity calculation.
      requestBody:
        description: a similarity job
        content:
          application/json:
            schema:
              $ref: './schemas/SimilarityJob.yaml'
      responses:
        "200":
          description: similarity job successfully calculated
          content:
            application/json:
              schema:
                description: similarity score for each reference spectrum in the order of the reference spectra list
                type: array
                items:
                  type: number
  
