FROM node:19-alpine AS build

WORKDIR /app

COPY web-frontend/package.json ./
RUN npm install
COPY web-frontend/static ./static
COPY web-frontend/src ./src
COPY web-frontend/svelte.config.js  web-frontend/tsconfig.json  web-frontend/vite.config.ts ./
COPY web-frontend/.svelte-kit/tsconfig.json ./.svelte-kit/
EXPOSE 5173
ENTRYPOINT ["npm", "run", "dev","--host"]

