FROM docker.io/golang:1.23 AS build
WORKDIR /go/src
COPY pkg/mb3dbtool/main.go ./cmd/mb3dbtool/
COPY pkg/ ./pkg
COPY go.mod .

ENV CGO_ENABLED=0
RUN go get -d -v ./...

RUN go build -a -installsuffix cgo -o mb3dbtool ./cmd/mb3dbtool

FROM docker.io/alpine:3.21 AS runtime
COPY --from=build /go/src/mb3dbtool ./
RUN printf 'case $MB_DB_INIT in\n\
  true) echo Initialize database...\n\
  ./mb3dbtool;;\n\
  *) echo Skip database initialization...;;\n\
  esac' > ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

EXPOSE 8080/tcp
CMD ["/bin/sh","./entrypoint.sh"]
