FROM node:19-alpine
# Create app directory
WORKDIR /app

# Bundle app source
COPY ./web-frontend/ .

# install dependencies
# RUN npm install --legacy-peer-deps
RUN npm install

# for production mode
RUN node ./node_modules/rimraf dist && node ./node_modules/typescript/bin/tsc && node ./node_modules/vite/bin/vite.js build

EXPOSE 5173
ENTRYPOINT ["npm", "run", "preview"]

