FROM golang:1.19 AS build
WORKDIR /go/src
COPY cmd/mb3dbtool/main.go ./cmd/mb3dbtool/
COPY pkg/ ./pkg
COPY go.mod .

RUN go get -d -v ./...

ENTRYPOINT ["go" ,"test", "-v","./...","-coverprofile", "out/cover.out"]