FROM node:19-alpine
# Create app directory
WORKDIR /app

# Bundle app source
COPY ./web-frontend/ .

# install dependencies
# RUN npm install --legacy-peer-deps
RUN npm install

# for production mode
RUN npm run build

ARG MB3_API_URL
RUN touch .env
RUN echo "VITE_MB3_API_URL=${MB3_API_URL}" > .env

EXPOSE 3000
CMD npm run start
