FROM node:19-alpine
# Create app directory
WORKDIR /app

# Bundle app source
COPY ./web-frontend/ .

# install dependencies
# RUN npm install --legacy-peer-deps
RUN npm install

# for production mode
RUN npm run build

ARG MB3_API_URL
ARG MB3_FRONTEND_URL
ARG MB3_FRONTEND_BASE_URL

ENTRYPOINT sh entrypoint.sh ${MB3_API_URL} ${MB3_FRONTEND_URL} ${MB3_FRONTEND_BASE_URL}

EXPOSE 3000