FROM docker.io/golang:1.22 AS build
WORKDIR /go/src
COPY cmd/mb3server/src ./cmd/mb3server/src
COPY cmd/mb3server/main.go ./cmd/mb3server
COPY pkg ./pkg
COPY go.mod .

RUN wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.20.2.tar.gz && \
    tar -xf v5.20.2.tar.gz && \
    mv swagger-ui-5.20.2/dist ./swagger-ui && \
    sed -i 's/url: \".*\"/url: \"\.\/openapi.yml\"/' swagger-ui/swagger-initializer.js && \
    mv swagger-ui cmd/mb3server/swagger-ui

COPY api/openapi.yml ./cmd/mb3server/swagger-ui/openapi.yml
COPY api/schemas ./cmd/mb3server/swagger-ui/schemas

ENV CGO_ENABLED=0
RUN go get -d -v ./...

RUN go build -a -installsuffix cgo -o mb3server ./cmd/mb3server

FROM scratch AS runtime
COPY --from=build /go/src/mb3server ./
EXPOSE 8080/tcp
ENTRYPOINT ["./mb3server"]
