FROM node:19-alpine
# Create app directory
WORKDIR /app

# Bundle app source
COPY ./web-frontend/ .

# install dependencies
RUN npm run clean-install

# for production mode
RUN export NODE_OPTIONS=--max-old-space-size=2048 && npm run build

ENTRYPOINT sh entrypoint.sh ${MB3_API_URL} ${MB3_FRONTEND_URL} ${MB3_FRONTEND_BASE_URL} "${MB3_FRONTEND_VERSION}" "${EXPORT_SERVICE_HOST}" "${EXPORT_SERVICE_PORT}"

EXPOSE 3000