/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

import (
	"context"
	"net/http"
)

// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	GetBrowseOptions(http.ResponseWriter, *http.Request)
	GetFilterOptions(http.ResponseWriter, *http.Request)
	GetMetadata(http.ResponseWriter, *http.Request)
	GetRecord(http.ResponseWriter, *http.Request)
	GetRecords(http.ResponseWriter, *http.Request)
}

// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	GetBrowseOptions(context.Context) (ImplResponse, error)
	GetFilterOptions(context.Context) (ImplResponse, error)
	GetMetadata(context.Context) (ImplResponse, error)
	GetRecord(context.Context, string) (ImplResponse, error)
	GetRecords(context.Context, []string, string, []string, string, string, string, float64, string, []string, int32, []string, []string, int32, int32, int32, string) (ImplResponse, error)
}
