/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

import (
	"context"
	"errors"
	"net/http"
)

// DefaultAPIService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() *DefaultAPIService {
	return &DefaultAPIService{}
}

// GetBrowseOptions - get browse options
func (s *DefaultAPIService) GetBrowseOptions(ctx context.Context, instrumentType []string, msType []string, ionMode string, contributor []string) (ImplResponse, error) {
	opt, err := GetBrowseOptions(instrumentType, msType, ionMode, contributor)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), errors.New("Could not get results")
	}
	return Response(http.StatusOK, opt), nil
}

// GetCount - get record count
func (s *DefaultAPIService) GetCount(ctx context.Context) (ImplResponse, error) {
	count, err := GetCount()
	if err != nil {
		return Response(http.StatusInternalServerError, nil), errors.New("Could not get result count")
	}

	return Response(200, count), nil
}

// GetMetadata - get massbank metadata
func (s *DefaultAPIService) GetMetadata(ctx context.Context) (ImplResponse, error) {	
	metadata, err := GetMetadata()
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}
	return Response(200, metadata), err
}

// GetRecord - Get a MassBank record
func (s *DefaultAPIService) GetRecord(ctx context.Context, accession string) (ImplResponse, error) {
	record, err := GetRecord(accession)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}
	return Response(200, record), err
}

// GetRecords - Get a list of records
func (s *DefaultAPIService) GetRecords(ctx context.Context, instrumentType []string, splash string, msType []string, ionMode string, compoundName string, compoundClass string, exactMass string, massTolerance float64, formula string, peaks []string, intensity int32, peakDifferences []string, peakList []string, inchi string, inchiKey string, contributor []string) (ImplResponse, error) {
	result, err := GetRecords(instrumentType, splash, msType, ionMode, compoundName, compoundClass, exactMass, massTolerance, formula, peaks, intensity, peakDifferences, peakList, inchi, inchiKey, contributor)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}
	return Response(200, result), nil
}

// GetRecords - Get a list of records
func (s *DefaultAPIService) GetVersion(ctx context.Context) (ImplResponse, error) {
	result, err := GetVersion()
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}
	return Response(200, result), nil
}

// GetSimilarity implements DefaultAPIServicer.
func (s *DefaultAPIService) GetSimilarity(ctx context.Context, peakList []string, referenceSpectraList []string, limit int32, threshold float64) (ImplResponse, error) {
	// TODO - update GetSimilarity with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	result, err := GetSimilarity(peakList, referenceSpectraList, limit, threshold)

	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}

	return Response(http.StatusOK, result), err
}

// GetSimpleRecord - Get a simple MassBank record
func (s *DefaultAPIService) GetSimpleRecord(ctx context.Context, accession string) (ImplResponse, error) {
	// TODO - update GetRecord with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	record, err := GetSimpleRecord(accession)
	return Response(200, record), err
}

// GetSimpleRecords - Get a list of records
func (s *DefaultAPIService) GetSearchResults(ctx context.Context, instrumentType []string, splash string, msType []string, ionMode string, compoundName string, compoundClass string,exactMass string, massTolerance float64, formula string, peaks []string, intensity int32, peakDifferences []string, peakList []string, peakListThreshold float64, inchi string, inchiKey string, contributor []string, substructure string) (ImplResponse, error) {
	result, err := GetSearchResults(instrumentType, splash, msType, ionMode, compoundName, compoundClass, exactMass, massTolerance, formula, peaks, intensity, peakDifferences, peakList, peakListThreshold, inchi, inchiKey, contributor, substructure)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}

	return Response(200, result), nil
}
