/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type ExactMass struct {
	Operator string `json:"operator,omitempty"`

	Mass float64 `json:"mass,omitempty"`

	Tolerance float64 `json:"tolerance,omitempty"`
}

// AssertExactMassRequired checks if the required fields are not zero-ed
func AssertExactMassRequired(obj ExactMass) error {
	return nil
}

// AssertRecurseExactMassRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ExactMass (e.g. [][]ExactMass), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseExactMassRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aExactMass, ok := obj.(ExactMass)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertExactMassRequired(aExactMass)
	})
}
