/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type StringCountInner struct {
	Value string `json:"value,omitempty"`

	Count int32 `json:"count,omitempty"`
}

// AssertStringCountInnerRequired checks if the required fields are not zero-ed
func AssertStringCountInnerRequired(obj StringCountInner) error {
	return nil
}

// AssertRecurseStringCountInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of StringCountInner (e.g. [][]StringCountInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStringCountInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStringCountInner, ok := obj.(StringCountInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStringCountInnerRequired(aStringCountInner)
	})
}
