/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// AuthorsInner - Name of the author or affiliation
type AuthorsInner struct {
	Name string `json:"name"`

	// Marc relator to describe contribution of author or affiliation
	MarcRelator string `json:"marc-relator,omitempty"`
}

// AssertAuthorsInnerRequired checks if the required fields are not zero-ed
func AssertAuthorsInnerRequired(obj AuthorsInner) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAuthorsInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AuthorsInner (e.g. [][]AuthorsInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuthorsInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuthorsInner, ok := obj.(AuthorsInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuthorsInnerRequired(aAuthorsInner)
	})
}
