/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type MetadataCompoundClassInner struct {
	Name string `json:"name,omitempty"`

	Count int32 `json:"count,omitempty"`
}

// AssertMetadataCompoundClassInnerRequired checks if the required fields are not zero-ed
func AssertMetadataCompoundClassInnerRequired(obj MetadataCompoundClassInner) error {
	return nil
}

// AssertRecurseMetadataCompoundClassInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MetadataCompoundClassInner (e.g. [][]MetadataCompoundClassInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMetadataCompoundClassInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMetadataCompoundClassInner, ok := obj.(MetadataCompoundClassInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMetadataCompoundClassInnerRequired(aMetadataCompoundClassInner)
	})
}
