/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type StringCount struct {
	Values []string `json:"values,omitempty"`

	Count int32 `json:"count,omitempty"`
}

// AssertStringCountRequired checks if the required fields are not zero-ed
func AssertStringCountRequired(obj StringCount) error {
	return nil
}

// AssertRecurseStringCountRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of StringCount (e.g. [][]StringCount), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStringCountRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStringCount, ok := obj.(StringCount)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStringCountRequired(aStringCount)
	})
}
