/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// MbRecordCommentsInnerOneOf - A annotated comment
type MbRecordCommentsInnerOneOf struct {

	// The subtag to describe the comment
	Subtag string `json:"subtag,omitempty"`

	// The comment
	Value string `json:"value,omitempty"`
}

// AssertMbRecordCommentsInnerOneOfRequired checks if the required fields are not zero-ed
func AssertMbRecordCommentsInnerOneOfRequired(obj MbRecordCommentsInnerOneOf) error {
	return nil
}

// AssertRecurseMbRecordCommentsInnerOneOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MbRecordCommentsInnerOneOf (e.g. [][]MbRecordCommentsInnerOneOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMbRecordCommentsInnerOneOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMbRecordCommentsInnerOneOf, ok := obj.(MbRecordCommentsInnerOneOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMbRecordCommentsInnerOneOfRequired(aMbRecordCommentsInnerOneOf)
	})
}
