/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// GetStatus200ResponsePostgres - The status of the postgres database.
type GetStatus200ResponsePostgres struct {

	// The status of the postgres database.
	Status string `json:"status,omitempty"`

	// The error message if the postgres database is not running.
	Error string `json:"error,omitempty"`
}

// AssertGetStatus200ResponsePostgresRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponsePostgresRequired(obj GetStatus200ResponsePostgres) error {
	return nil
}

// AssertRecurseGetStatus200ResponsePostgresRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetStatus200ResponsePostgres (e.g. [][]GetStatus200ResponsePostgres), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetStatus200ResponsePostgresRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetStatus200ResponsePostgres, ok := obj.(GetStatus200ResponsePostgres)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetStatus200ResponsePostgresRequired(aGetStatus200ResponsePostgres)
	})
}
