/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// MbRecordPeakPeakValuesInner - Values for a single peak
type MbRecordPeakPeakValuesInner struct {

	// m/z of the peak
	Mz float32 `json:"mz,omitempty"`

	// intensity of the peak
	Intensity float64 `json:"intensity,omitempty"`

	// Relative intensity of the peak
	Rel uint16 `json:"rel,omitempty"`
}

// AssertMbRecordPeakPeakValuesInnerRequired checks if the required fields are not zero-ed
func AssertMbRecordPeakPeakValuesInnerRequired(obj MbRecordPeakPeakValuesInner) error {
	return nil
}

// AssertRecurseMbRecordPeakPeakValuesInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MbRecordPeakPeakValuesInner (e.g. [][]MbRecordPeakPeakValuesInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMbRecordPeakPeakValuesInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMbRecordPeakPeakValuesInner, ok := obj.(MbRecordPeakPeakValuesInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMbRecordPeakPeakValuesInnerRequired(aMbRecordPeakPeakValuesInner)
	})
}
