/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type PeakList struct {
	Peaks []PeakListPeaksInner `json:"peaks,omitempty"`

	IntensityCutoff int32 `json:"intensity_cutoff,omitempty"`

	Limit int32 `json:"limit,omitempty"`
}

// AssertPeakListRequired checks if the required fields are not zero-ed
func AssertPeakListRequired(obj PeakList) error {
	for _, el := range obj.Peaks {
		if err := AssertPeakListPeaksInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecursePeakListRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PeakList (e.g. [][]PeakList), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePeakListRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPeakList, ok := obj.(PeakList)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPeakListRequired(aPeakList)
	})
}
