/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type Peaks struct {
	Peaks []PeaksPeaksInner `json:"peaks,omitempty"`

	Intensity int32 `json:"intensity,omitempty"`
}

// AssertPeaksRequired checks if the required fields are not zero-ed
func AssertPeaksRequired(obj Peaks) error {
	for _, el := range obj.Peaks {
		if err := AssertPeaksPeaksInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecursePeaksRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Peaks (e.g. [][]Peaks), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePeaksRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPeaks, ok := obj.(Peaks)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPeaksRequired(aPeaks)
	})
}
