/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type MetadataCompoundNameInner struct {
	Name string `json:"name,omitempty"`

	Count int32 `json:"count,omitempty"`
}

// AssertMetadataCompoundNameInnerRequired checks if the required fields are not zero-ed
func AssertMetadataCompoundNameInnerRequired(obj MetadataCompoundNameInner) error {
	return nil
}

// AssertRecurseMetadataCompoundNameInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MetadataCompoundNameInner (e.g. [][]MetadataCompoundNameInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMetadataCompoundNameInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMetadataCompoundNameInner, ok := obj.(MetadataCompoundNameInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMetadataCompoundNameInnerRequired(aMetadataCompoundNameInner)
	})
}
