/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type FilterOptionsIntensity struct {
	Minimum int32 `json:"minimum,omitempty"`

	Maximum int32 `json:"maximum,omitempty"`
}

// AssertFilterOptionsIntensityRequired checks if the required fields are not zero-ed
func AssertFilterOptionsIntensityRequired(obj FilterOptionsIntensity) error {
	return nil
}

// AssertRecurseFilterOptionsIntensityRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FilterOptionsIntensity (e.g. [][]FilterOptionsIntensity), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFilterOptionsIntensityRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFilterOptionsIntensity, ok := obj.(FilterOptionsIntensity)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFilterOptionsIntensityRequired(aFilterOptionsIntensity)
	})
}
