/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// MbRecordDate - Date of creation or last modification of record
type MbRecordDate struct {

	// Date of last update to record
	Updated string `json:"updated,omitempty"`

	// Date of record creation
	Created string `json:"created,omitempty"`

	// Date of last (automatic) modification to record
	Modified string `json:"modified,omitempty"`
}

// AssertMbRecordDateRequired checks if the required fields are not zero-ed
func AssertMbRecordDateRequired(obj MbRecordDate) error {
	return nil
}

// AssertRecurseMbRecordDateRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MbRecordDate (e.g. [][]MbRecordDate), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMbRecordDateRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMbRecordDate, ok := obj.(MbRecordDate)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMbRecordDateRequired(aMbRecordDate)
	})
}
