/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type FilterOptionsMass struct {
	Minimum float64 `json:"minimum,omitempty"`

	Maximum float64 `json:"maximum,omitempty"`
}

// AssertFilterOptionsMassRequired checks if the required fields are not zero-ed
func AssertFilterOptionsMassRequired(obj FilterOptionsMass) error {
	return nil
}

// AssertRecurseFilterOptionsMassRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FilterOptionsMass (e.g. [][]FilterOptionsMass), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFilterOptionsMassRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFilterOptionsMass, ok := obj.(FilterOptionsMass)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFilterOptionsMassRequired(aFilterOptionsMass)
	})
}
