/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// MsFocusedIonInner - A list of subtag value pairs
type MsFocusedIonInner struct {

	// Subtag describing the value
	Subtag string `json:"subtag,omitempty"`

	// The value for the subtag
	Value string `json:"value,omitempty"`
}

// AssertMsFocusedIonInnerRequired checks if the required fields are not zero-ed
func AssertMsFocusedIonInnerRequired(obj MsFocusedIonInner) error {
	return nil
}

// AssertRecurseMsFocusedIonInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MsFocusedIonInner (e.g. [][]MsFocusedIonInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMsFocusedIonInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMsFocusedIonInner, ok := obj.(MsFocusedIonInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMsFocusedIonInnerRequired(aMsFocusedIonInner)
	})
}
