/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type BrowseOptions struct {
	Metadata Metadata `json:"metadata,omitempty"`

	Contributor []StringCountInner `json:"contributor,omitempty"`

	InstrumentType []StringCountInner `json:"instrument_type,omitempty"`

	MsType []StringCountInner `json:"ms_type,omitempty"`

	IonMode []StringCountInner `json:"ion_mode,omitempty"`

	CompoundStart []StringCountInner `json:"compound_start,omitempty"`
}

// AssertBrowseOptionsRequired checks if the required fields are not zero-ed
func AssertBrowseOptionsRequired(obj BrowseOptions) error {
	if err := AssertMetadataRequired(obj.Metadata); err != nil {
		return err
	}
	for _, el := range obj.Contributor {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.InstrumentType {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.MsType {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.IonMode {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.CompoundStart {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseBrowseOptionsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BrowseOptions (e.g. [][]BrowseOptions), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBrowseOptionsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBrowseOptions, ok := obj.(BrowseOptions)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBrowseOptionsRequired(aBrowseOptions)
	})
}
