/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// MsDataProcessingInner - A list of subtag value pairs
type MsDataProcessingInner struct {

	// Subtag describing the value
	Subtag string `json:"subtag,omitempty"`

	// The value for the subtag
	Value string `json:"value,omitempty"`
}

// AssertMsDataProcessingInnerRequired checks if the required fields are not zero-ed
func AssertMsDataProcessingInnerRequired(obj MsDataProcessingInner) error {
	return nil
}

// AssertRecurseMsDataProcessingInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MsDataProcessingInner (e.g. [][]MsDataProcessingInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMsDataProcessingInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMsDataProcessingInner, ok := obj.(MsDataProcessingInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMsDataProcessingInnerRequired(aMsDataProcessingInner)
	})
}
