/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type AcMassSpecSubtagsInner struct {
	Subtag string `json:"subtag,omitempty"`

	Value string `json:"value,omitempty"`
}

// AssertAcMassSpecSubtagsInnerRequired checks if the required fields are not zero-ed
func AssertAcMassSpecSubtagsInnerRequired(obj AcMassSpecSubtagsInner) error {
	return nil
}

// AssertRecurseAcMassSpecSubtagsInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AcMassSpecSubtagsInner (e.g. [][]AcMassSpecSubtagsInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAcMassSpecSubtagsInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAcMassSpecSubtagsInner, ok := obj.(AcMassSpecSubtagsInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAcMassSpecSubtagsInnerRequired(aAcMassSpecSubtagsInner)
	})
}
