/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// MbRecordSpecies - Information of Biological Sample
type MbRecordSpecies struct {

	// Scientific name of biological species
	Name string `json:"name,omitempty"`

	// Lineage of species
	Lineage []string `json:"lineage,omitempty"`

	// External database name with identifier
	Link []DatabaseObject `json:"link,omitempty"`

	// Information of sample preparation
	Sample []string `json:"sample,omitempty"`
}

// AssertMbRecordSpeciesRequired checks if the required fields are not zero-ed
func AssertMbRecordSpeciesRequired(obj MbRecordSpecies) error {
	for _, el := range obj.Link {
		if err := AssertDatabaseObjectRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseMbRecordSpeciesRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MbRecordSpecies (e.g. [][]MbRecordSpecies), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMbRecordSpeciesRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMbRecordSpecies, ok := obj.(MbRecordSpecies)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMbRecordSpeciesRequired(aMbRecordSpecies)
	})
}
