/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type GetStatus200Response struct {
	Postgres GetStatus200ResponsePostgres `json:"postgres,omitempty"`

	ExportService GetStatus200ResponseExportService `json:"export_service,omitempty"`

	SimilarityService GetStatus200ResponseSimilarityService `json:"similarity_service,omitempty"`
}

// AssertGetStatus200ResponseRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponseRequired(obj GetStatus200Response) error {
	if err := AssertGetStatus200ResponsePostgresRequired(obj.Postgres); err != nil {
		return err
	}
	if err := AssertGetStatus200ResponseExportServiceRequired(obj.ExportService); err != nil {
		return err
	}
	if err := AssertGetStatus200ResponseSimilarityServiceRequired(obj.SimilarityService); err != nil {
		return err
	}
	return nil
}

// AssertRecurseGetStatus200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetStatus200Response (e.g. [][]GetStatus200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetStatus200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetStatus200Response, ok := obj.(GetStatus200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetStatus200ResponseRequired(aGetStatus200Response)
	})
}
