/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// DatabaseObject - A database entry
type DatabaseObject struct {

	// Abbreviation for Database
	Database string `json:"database,omitempty"`

	// Identifier of the database record
	Identifier string `json:"identifier,omitempty"`
}

// AssertDatabaseObjectRequired checks if the required fields are not zero-ed
func AssertDatabaseObjectRequired(obj DatabaseObject) error {
	return nil
}

// AssertRecurseDatabaseObjectRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DatabaseObject (e.g. [][]DatabaseObject), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDatabaseObjectRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDatabaseObject, ok := obj.(DatabaseObject)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDatabaseObjectRequired(aDatabaseObject)
	})
}
