/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// MbRecordPeakAnnotation - Chemical Annotation of Peaks with Molecular Formula
type MbRecordPeakAnnotation struct {

	// Record format of the annotation blocks
	Header []string `json:"header,omitempty"`

	// Annotation blocks
	Values [][]string `json:"values,omitempty"`
}

// AssertMbRecordPeakAnnotationRequired checks if the required fields are not zero-ed
func AssertMbRecordPeakAnnotationRequired(obj MbRecordPeakAnnotation) error {
	return nil
}

// AssertRecurseMbRecordPeakAnnotationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MbRecordPeakAnnotation (e.g. [][]MbRecordPeakAnnotation), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMbRecordPeakAnnotationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMbRecordPeakAnnotation, ok := obj.(MbRecordPeakAnnotation)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMbRecordPeakAnnotationRequired(aMbRecordPeakAnnotation)
	})
}
