/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type Formula struct {
	Operator string `json:"operator,omitempty"`

	Formula string `json:"formula,omitempty"`
}

// AssertFormulaRequired checks if the required fields are not zero-ed
func AssertFormulaRequired(obj Formula) error {
	return nil
}

// AssertRecurseFormulaRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Formula (e.g. [][]Formula), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFormulaRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFormula, ok := obj.(Formula)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFormulaRequired(aFormula)
	})
}
