/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type AcChromatographyInner struct {
	Subtag string `json:"subtag,omitempty"`

	Value string `json:"value,omitempty"`
}

// AssertAcChromatographyInnerRequired checks if the required fields are not zero-ed
func AssertAcChromatographyInnerRequired(obj AcChromatographyInner) error {
	return nil
}

// AssertRecurseAcChromatographyInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AcChromatographyInner (e.g. [][]AcChromatographyInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAcChromatographyInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAcChromatographyInner, ok := obj.(AcChromatographyInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAcChromatographyInnerRequired(aAcChromatographyInner)
	})
}
