/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// GetStatus200ResponseSimilarityService - The status of the similarity service.
type GetStatus200ResponseSimilarityService struct {

	// The status of the similarity service.
	Status string `json:"status,omitempty"`

	// The error message if the similarity service is not running.
	Error string `json:"error,omitempty"`
}

// AssertGetStatus200ResponseSimilarityServiceRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponseSimilarityServiceRequired(obj GetStatus200ResponseSimilarityService) error {
	return nil
}

// AssertRecurseGetStatus200ResponseSimilarityServiceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetStatus200ResponseSimilarityService (e.g. [][]GetStatus200ResponseSimilarityService), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetStatus200ResponseSimilarityServiceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetStatus200ResponseSimilarityService, ok := obj.(GetStatus200ResponseSimilarityService)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetStatus200ResponseSimilarityServiceRequired(aGetStatus200ResponseSimilarityService)
	})
}
