/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type IonMode string

// List of IonMode
const (
	POSITIVE IonMode = "POSITIVE"
	NEGATIVE IonMode = "NEGATIVE"
)

// AssertIonModeRequired checks if the required fields are not zero-ed
func AssertIonModeRequired(obj IonMode) error {
	return nil
}

// AssertRecurseIonModeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IonMode (e.g. [][]IonMode), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIonModeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIonMode, ok := obj.(IonMode)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIonModeRequired(aIonMode)
	})
}
