/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// GetStatus200ResponseExportService - The status of the export service.
type GetStatus200ResponseExportService struct {

	// The status of the export service.
	Status string `json:"status,omitempty"`

	// The error message if the export service is not running.
	Error string `json:"error,omitempty"`
}

// AssertGetStatus200ResponseExportServiceRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponseExportServiceRequired(obj GetStatus200ResponseExportService) error {
	return nil
}

// AssertRecurseGetStatus200ResponseExportServiceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetStatus200ResponseExportService (e.g. [][]GetStatus200ResponseExportService), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetStatus200ResponseExportServiceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetStatus200ResponseExportService, ok := obj.(GetStatus200ResponseExportService)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetStatus200ResponseExportServiceRequired(aGetStatus200ResponseExportService)
	})
}
