/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type AcGeneralInner struct {
	Subtag string `json:"subtag,omitempty"`

	Value string `json:"value,omitempty"`
}

// AssertAcGeneralInnerRequired checks if the required fields are not zero-ed
func AssertAcGeneralInnerRequired(obj AcGeneralInner) error {
	return nil
}

// AssertRecurseAcGeneralInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AcGeneralInner (e.g. [][]AcGeneralInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAcGeneralInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAcGeneralInner, ok := obj.(AcGeneralInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAcGeneralInnerRequired(aAcGeneralInner)
	})
}
