/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

type MbRecordMassSpectrometry struct {
	FocusedIon []MsFocusedIonInner `json:"focused_ion,omitempty"`

	DataProcessing []MsDataProcessingInner `json:"data_processing,omitempty"`
}

// AssertMbRecordMassSpectrometryRequired checks if the required fields are not zero-ed
func AssertMbRecordMassSpectrometryRequired(obj MbRecordMassSpectrometry) error {
	for _, el := range obj.FocusedIon {
		if err := AssertMsFocusedIonInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.DataProcessing {
		if err := AssertMsDataProcessingInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseMbRecordMassSpectrometryRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MbRecordMassSpectrometry (e.g. [][]MbRecordMassSpectrometry), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMbRecordMassSpectrometryRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMbRecordMassSpectrometry, ok := obj.(MbRecordMassSpectrometry)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMbRecordMassSpectrometryRequired(aMbRecordMassSpectrometry)
	})
}
