/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mb3server

// MbRecordPeakPeak - Peak Data
type MbRecordPeakPeak struct {

	// Fixed header
	Header []string `json:"header,omitempty"`

	// Peak values
	Values []MbRecordPeakPeakValuesInner `json:"values,omitempty"`
}

// AssertMbRecordPeakPeakRequired checks if the required fields are not zero-ed
func AssertMbRecordPeakPeakRequired(obj MbRecordPeakPeak) error {
	for _, el := range obj.Values {
		if err := AssertMbRecordPeakPeakValuesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseMbRecordPeakPeakRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MbRecordPeakPeak (e.g. [][]MbRecordPeakPeak), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMbRecordPeakPeakRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMbRecordPeakPeak, ok := obj.(MbRecordPeakPeak)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMbRecordPeakPeakRequired(aMbRecordPeakPeak)
	})
}
