apiVersion: v1
kind: ConfigMap
metadata:
  name: massbank3-frontend-secret
  namespace: massbank3
  labels:
    app: massbank3-frontend
data:
  MB3_API_URL: "https://msbi.ipb-halle.de/MassBank-api"
  MB3_API_URL_INTERNAL: "http://massbank3-server-service:8080"
  MB3_FRONTEND_URL: "https://msbi.ipb-halle.de"
  MB3_FRONTEND_BASE_URL: "/MassBank/"
  MB3_FRONTEND_VERSION: "0.4.0 (beta)"
  EXPORT_SERVICE_URL: "https://msbi.ipb-halle.de/MassBank-export"
  EXPORT_SERVICE_URL_INTERNAL: "http://massbank3-export-service-service:8080"
  GOOGLE_SEARCH_CONSOLE_KEY: "4aoZgYg2lHeh7TlOxtyVzjHa3YJirrsEHPqwSU3luoU"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: massbank3-frontend-deployment # Name des Deployments für uns Nutzer
  namespace: massbank3
  labels:
    app: massbank3-frontend # Labels des Deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: massbank3-frontend # Welche Container gehören zum Deployment? (*)
  template:
    metadata:
      labels:
        app: massbank3-frontend # Label des Pods muss/ sollte mit (*) übereinstimmen
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - massbank3-server
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: massbank3-frontend
          image: ipbhalle/massbank3-frontend:dev # Container Image
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name:
                  massbank3-frontend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: massbank3-frontend-service
  namespace: massbank3
spec:
  type: NodePort
  selector:
    app: massbank3-frontend # Das gleiche Label wie im Deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: massbank3-frontend
  name: massbank3-frontend-ingress
  namespace: massbank3
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: msbi.ipb-halle.de
      http:
        paths:
          - backend:
              service:
                name: massbank3-frontend-service
                port:
                  number: 3000
            path: /MassBank(/|$)(.*)
            pathType: ImplementationSpecific
