apiVersion: v1
kind: ConfigMap
metadata:
  name: massbank3-frontend-secret
  namespace: massbank3
  labels:
    app: massbank3-frontend
data:
  MB3_API_URL: "https://msbi.ipb-halle.de/MassBank3-api/"
  MB3_FRONTEND_URL: "https://msbi.ipb-halle.de"
  MB3_FRONTEND_BASE_URL: "/MassBank3/"
  EXPORT_SERVICE_URL: "https://msbi.ipb-halle.de/MassBank3-export/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: massbank3-frontend-deployment # Name des Deployments für uns Nutzer
  namespace: massbank3
  labels:
    app: massbank3-frontend # Labels des Deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: massbank3-frontend # Welche Container gehören zum Deployment? (*)
  template:
    metadata:
      labels:
        app: massbank3-frontend # Label des Pods muss/ sollte mit (*) übereinstimmen
    spec:
      containers:
        - name: massbank3-frontend
          image: ipbhalle/massbank3-frontend:dev # Container Image
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name:
                  massbank3-frontend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: massbank3-frontend-service
  namespace: massbank3
spec:
  type: NodePort
  selector:
    app: massbank3-frontend # Das gleiche Label wie im Deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: massbank3-frontend
  name: massbank3-frontend-ingress
  namespace: massbank3
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: msbi.ipb-halle.de
      http:
        paths:
          - backend:
              service:
                name: massbank3-frontend-service
                port:
                  number: 3000
            path: /MassBank3(/|$)(.*)
            pathType: ImplementationSpecific
