apiVersion: v1
kind: ConfigMap
metadata:
  name: massbank3-postgres-secret
  namespace: massbank3
  labels:
    app: massbank3-postgres
data:
  POSTGRES_DB: "massbank3"
  POSTGRES_USER: "massbank3"
  POSTGRES_PASSWORD: "massbank3password"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: massbank3-postgres-volume
  namespace: massbank3
  labels:
    type: local
    app: massbank3-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: massbank3-postgres-volume-claim
  namespace: massbank3
  labels:
    app: massbank3-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: massbank3-postgres-deployment # Name des Deployments für uns Nutzer
  namespace: massbank3
  labels:
    app: massbank3-postgres # Labels des Deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: massbank3-postgres # Welche Container gehören zum Deployment? (*)
  template:
    metadata:
      labels:
        app: massbank3-postgres  # Label des Pods muss/ sollte mit (*) übereinstimmen
    spec:
      containers:
        - name: massbank3-postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: massbank3-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: massbank3-postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: massbank3-postgres-service
  labels:
    app: massbank3-postgres
spec:
  type: NodePort
  selector:
    app: massbank3-postgres
  ports:
    - port: 5432


