apiVersion: v1
kind: ConfigMap
metadata:
  name: massbank3-postgres-secret
  namespace: massbank3
  labels:
    app: massbank3-postgres
data:
  POSTGRES_DB: "massbank3"
  POSTGRES_USER: "massbank3"
  POSTGRES_PASSWORD: "massbank3password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: massbank3-bingo-init
  namespace: massbank3
  labels:
    app: massbank3-postgres
data:
  init.sh: |
    #!/bin/bash
    set -e
  
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- update ALLOW_NON_UNIQUE_DEAROMATIZATION to 1 --
    UPDATE bingo.bingo_config SET cvalue = 1 WHERE cname = 'ALLOW_NON_UNIQUE_DEAROMATIZATION';
    EOSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: massbank3-postgres-volume-claim
  namespace: massbank3
  labels:
    app: massbank3-postgres
spec:
  storageClassName: nfs-unity
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: massbank3-postgres-deployment # Name des Deployments für uns Nutzer
  namespace: massbank3
  labels:
    app: massbank3-postgres # Labels des Deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: massbank3-postgres # Welche Container gehören zum Deployment? (*)
  template:
    metadata:
      labels:
        app: massbank3-postgres  # Label des Pods muss/ sollte mit (*) übereinstimmen
    spec:
      containers:
        - name: massbank3-postgres
          image: 'ipbhalle/postgres:15-bingo-1.24.0'
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: massbank3-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
            - mountPath: "/docker-entrypoint-initdb.d/init.sh"
              name: bingo-init
              subPath: "init.sh"
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: massbank3-postgres-volume-claim
        - name: bingo-init
          configMap:
            name: massbank3-bingo-init
            defaultMode: 0555
---
apiVersion: v1
kind: Service
metadata:
  name: massbank3-postgres-service
  labels:
    app: massbank3-postgres
spec:
  type: NodePort
  selector:
    app: massbank3-postgres
  ports:
    - port: 5432


