version: '3.1'

services:

  testmongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mbtestuser"
      MONGO_INITDB_ROOT_PASSWORD: "mbtestpwd"

  testpostgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "mbtestpwd"
      POSTGRES_USER:     "mbtestuser"
      POSTGRES_DB:       "mbtestdb"

  mb3test:
    build:
      context: ..
      dockerfile: Dockerfile-test
    volumes:
      - ./testout:/go/src/out
    depends_on:
      - testmongo
      - testpostgres
