services:
  mongodb:
    ports:
      - "27017:27017"
  mb3server:
    build:
      context: ..
      dockerfile: Dockerfile-debug
    ports:
      - "40000:40000"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "apparmor=unconfined"
    volumes:
      - ./debuglog:/var/log