version: "3.1"

services:
  testpostgres:
    extends:
      file: docker-compose-common.yaml
      service: postgres
    environment:
      POSTGRES_PASSWORD: "mbtestpwd"
      POSTGRES_USER: "mbtestuser"
      POSTGRES_DB: "mbtestdb"

  mb3server:
    extends:
      file: docker-compose-common.yaml
      service: mb3server
    build: ../
    depends_on:
      testpostgres:
        condition: service_healthy

  mb3test:
    build:
      context: ..
      dockerfile: Dockerfile-test
    volumes:
      - ./testout:/go/src/out
    depends_on:
      testpostgres:
        condition: service_healthy
