version: '3.1'
services:
  mongodb:
    ports:
      - "27017:27017"
  postgres:
    ports:
      - "5432:5432"
  mb3server:
    build:
      context: ..
      dockerfile: Dockerfile-debug
    ports:
      - "40000:40000"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "apparmor=unconfined"
    volumes:
      - ./debuglog:/var/log
  mb3tool:
    build:
      context: ..
      dockerfile: Dockerfile-dbtool
    environment:
      - DB_TYPE
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
      - DB_CONN_STRING
      - MB_GIT_REPO
      - MB_GIT_BRANCH
      - MB_DATA_DIRECTORY
      - MB_DROP_ALL
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
  mb3frontend:
    build:
      context: ..
      dockerfile: Dockerfile-svelte-debug
    ports:
      - "${MB3_FRONTEND_PORT}:5173"
    volumes:
      - ../web-frontend:/app