version: '3.1'
services:
  mongodb:
    ports:
      - "27017:27017"
  postgres:
    ports:
      - "5432:5432"
  mb3server:
    build:
      context: ..
      dockerfile: Dockerfile-debug
    ports:
      - "40000:40000"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "apparmor=unconfined"
    volumes:
      - ./debuglog:/var/log
  mb3frontend:
    build:
      context: ..
      dockerfile: Dockerfile-svelte-debug
    ports:
      - "${MB3_FRONTEND_PORT}:5173"
    volumes:
      - ../web-frontend:/app

  cdkdepict:
    ports:
      - "8085:8080"
