version: '3.1'

services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test:  ["CMD","mongosh", "--eval", "\"db.adminCommand('ping')\""]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}","-U", "${DB_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s

  mb3server:
    restart: always
    ports:
      - "${MB3_API_PORT}:${SERVER_PORT}"
    environment:
      - DB_TYPE
      - DB_PORT
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
      - DB_CONN_STRING
      - SERVER_PORT
      - CDKDEPICT_URL
    depends_on:
      - mongodb
      - postgres

  mb3frontend:
    restart: always
    environment:
      VITE_SERVER_API_URL: "http://${MB3_API_HOST}:${MB3_API_PORT}"

  cdkdepict:
    image: simolecule/cdkdepict:latest
