mb3tool:
  build:
    context: ..
    dockerfile: Dockerfile-dbtool
  environment:
    - DB_TYPE
    - DB_PORT
    - DB_USER
    - DB_PASSWORD
    - DB_HOST
    - DB_NAME
    - DB_CONN_STRING
    - MB_GIT_REPO
    - MB_GIT_BRANCH
    - MB_DATA_DIRECTORY
    - MB_DROP_ALL
  depends_on:
    postgres:
      condition: service_healthy
    mongodb:
      condition: service_healthy
