version: "3.1"

services:
  postgres:
    extends:
      file: docker-compose-common.yaml
      service: postgres
    ports:
      - "5432:5432"

  mb3server:
    extends:
      file: docker-compose-common.yaml
      service: mb3server
    build:
      context: ..
      dockerfile: Dockerfile-debug
    ports:
      - "40000:40000"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "apparmor=unconfined"
    volumes:
      - ./debuglog:/var/log
    depends_on:
      - postgres

  mb3frontend:
    extends:
      file: docker-compose-common.yaml
      service: mb3frontend
    build:
      context: ..
      dockerfile: Dockerfile-frontend-debug
    environment:
      VITE_SERVER_API_URL: "http://${MB3_API_HOST}:${MB3_API_PORT}"
    ports:
      - "127.0.0.1:${MB3_FRONTEND_PORT}:5173/tcp"

  mb3tool:
    extends:
      file: docker-compose-common.yaml
      service: mb3tool
    depends_on:
      postgres:
        condition: service_healthy

  cdkdepict:
    extends:
      file: docker-compose-common.yaml
      service: cdkdepict
    ports:
      - "8085:8080"
