version: '3.1'

services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
    healthcheck:
      test:  ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB_NAME}","-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s

  mb3server:
    restart: always
    ports:
      - "${MB3_API_PORT}:8080"
    environment:
      MONGO_URI: "mongodb://${MONGODB_USER}:${MONGODB_PWD}@mongodb:27017"
      MONGO_DB_NAME: "massbank3"
    depends_on:
      - mongodb
      - postgres

  mb3frontend:
    restart: always
    environment:
      VITE_SERVER_API_URL: "http://localhost:8081"
