version: '3.1'

services:

  testmongo:
    image: docker.io/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mbtestuser"
      MONGO_INITDB_ROOT_PASSWORD: "mbtestpwd"
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "\"db.adminCommand('ping')\"" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  testpostgres:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "mbtestpwd"
      POSTGRES_USER:     "mbtestuser"
      POSTGRES_DB:       "mbtestdb"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB_NAME}","-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  mb3server:
    build: ../
  mb3test:
    build:
      context: ..
      dockerfile: Dockerfile-test
    volumes:
      - ./testout:/go/src/out
    depends_on:
      testpostgres:
        condition: service_healthy
      testmongo:
        condition: service_healthy
