version: "3.1"

services:
  mongodb:
    extends:
      file: docker-compose-common.yaml
      service: mongodb

  postgres:
    extends:
      file: docker-compose-common.yaml
      service: postgres

  mb3server:
    extends:
      file: docker-compose-common.yaml
      service: mb3server
    build: ../
    depends_on:
      - mongodb
      - postgres

  mb3frontend:
    extends:
      file: docker-compose-common.yaml
      service: mb3frontend
    build:
      context: ..
      dockerfile: Dockerfile-frontend
      args:
        MB3_API_URL: "http://${MB3_API_HOST}:${MB3_API_PORT}"
        MB3_FRONTEND_BASE_URL: "${MB3_FRONTEND_BASE_URL}"
    ports:
      - "${MB3_FRONTEND_PORT}:3000"

  cdkdepict:
    extends:
      file: docker-compose-common.yaml
      service: cdkdepict

  mb3tool:
    extends:
      file: docker-compose-common.yaml
      service: mb3tool
    profiles:
      - dbinit
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
