FROM node:23-alpine AS build
WORKDIR /app
# Installing dependencies first can save time on rebuilds
# We do need the full (dev) dependencies here
COPY package.json ./
RUN npm run clean-install
# Then copy in the actual sources we need and build
COPY tsconfig.json tsconfig.node.json vite.config.ts vite-env.d.ts server.ts server-utils.ts index.html entrypoint.sh ./
COPY src/ ./src/
COPY public/ ./public/
RUN npm run build

COPY mb_version.txt ./

FROM node:23-alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules/
COPY --from=build /app/dist ./dist/
COPY --from=build /app/src ./src/
COPY --from=build /app/public ./public/
COPY --from=build /app/package.json /app/package-lock.json /app/server.ts /app/server-utils.ts /app/entrypoint.sh ./
COPY --from=build /app/mb_version.txt ./

ENTRYPOINT sh entrypoint.sh "${MB3_API_URL}" "${MB3_FRONTEND_URL}" "${MB3_FRONTEND_BASE_URL}" "${EXPORT_SERVICE_URL}" "${MB3_API_URL_INTERNAL}" "${EXPORT_SERVICE_URL_INTERNAL}" "${DISTRIBUTOR_TEXT}" "${DISTRIBUTOR_URL}" "${MB3_FRONTEND_BROWSER_TAB_TITLE}" "${MB3_FRONTEND_HOMEPAGE_INTRO_TEXT}" "${MB3_FRONTEND_HOMEPAGE_NEWS_SECTION_TEXT}" "${MB3_FRONTEND_HOMEPAGE_FUNDING_SECTION_TEXT}" "${MB3_FRONTEND_HOMEPAGE_ADDITIONAL_SECTION_NAME}" "${MB3_FRONTEND_HOMEPAGE_ADDITIONAL_SECTION_TEXT}" "${HTML_HEAD_FILE}" "${HTML_BODY_FILE}"
EXPOSE 3000