// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * The MassBank3 API allows retrieval and filtering of records by chemical or experimental parameters, similarity search on peak lists, and access to individual record details, metadata, service status, and available filter options.
 *
 * API version: 3.0
 */

package mb3server

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
