// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * The MassBank3 API allows retrieval and filtering of records by chemical or experimental parameters, similarity search on peak lists, and access to individual record details, metadata, service status, and available filter options.
 *
 * API version: 3.0
 */

package mb3server

import (
	"net/http"
	"github.com/go-chi/chi/v5/middleware"
)

func Logger(inner http.Handler) http.Handler {
	return middleware.Logger(inner)
}
