// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server

import (
	"net/http"
	"github.com/go-chi/chi/v5/middleware"
)

func Logger(inner http.Handler) http.Handler {
	return middleware.Logger(inner)
}
