// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




type BrowseOptions struct {

	Contributor []StringCountInner `json:"contributor,omitempty"`

	InstrumentType []StringCountInner `json:"instrument_type,omitempty"`

	MsType []StringCountInner `json:"ms_type,omitempty"`

	IonMode []StringCountInner `json:"ion_mode,omitempty"`
}

// AssertBrowseOptionsRequired checks if the required fields are not zero-ed
func AssertBrowseOptionsRequired(obj BrowseOptions) error {
	for _, el := range obj.Contributor {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.InstrumentType {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.MsType {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.IonMode {
		if err := AssertStringCountInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertBrowseOptionsConstraints checks if the values respects the defined constraints
func AssertBrowseOptionsConstraints(obj BrowseOptions) error {
	for _, el := range obj.Contributor {
		if err := AssertStringCountInnerConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.InstrumentType {
		if err := AssertStringCountInnerConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.MsType {
		if err := AssertStringCountInnerConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.IonMode {
		if err := AssertStringCountInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
