// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * The MassBank3 API allows retrieval and filtering of records by chemical or experimental parameters, similarity search on peak lists, and access to individual record details, metadata, service status, and available filter options.
 *
 * API version: 3.0
 */

package mb3server




// GetStatus200ResponseApi - The status of the API.
type GetStatus200ResponseApi struct {

	// The status of the API.
	Status string `json:"status,omitempty"`

	// The version of the API.
	Version string `json:"version,omitempty"`

	// The error message if the API is not running.
	Error string `json:"error,omitempty"`
}

// AssertGetStatus200ResponseApiRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponseApiRequired(obj GetStatus200ResponseApi) error {
	return nil
}

// AssertGetStatus200ResponseApiConstraints checks if the values respects the defined constraints
func AssertGetStatus200ResponseApiConstraints(obj GetStatus200ResponseApi) error {
	return nil
}
