// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// GetStatus200ResponsePostgres - The status of the postgres database.
type GetStatus200ResponsePostgres struct {

	// The status of the postgres database.
	Status string `json:"status,omitempty"`

	// The error message if the postgres database is not running.
	Error string `json:"error,omitempty"`
}

// AssertGetStatus200ResponsePostgresRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponsePostgresRequired(obj GetStatus200ResponsePostgres) error {
	return nil
}

// AssertGetStatus200ResponsePostgresConstraints checks if the values respects the defined constraints
func AssertGetStatus200ResponsePostgresConstraints(obj GetStatus200ResponsePostgres) error {
	return nil
}
