// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// MbRecordDeprecated - Mark the record as deprecated
type MbRecordDeprecated struct {

	// Date of deprecation
	Date string `json:"date,omitempty"`

	// reason for deprecation
	Reason string `json:"reason,omitempty"`
}

// AssertMbRecordDeprecatedRequired checks if the required fields are not zero-ed
func AssertMbRecordDeprecatedRequired(obj MbRecordDeprecated) error {
	return nil
}

// AssertMbRecordDeprecatedConstraints checks if the values respects the defined constraints
func AssertMbRecordDeprecatedConstraints(obj MbRecordDeprecated) error {
	return nil
}
