// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// MbRecordPeakAnnotation - Chemical Annotation of Peaks with Molecular Formula
type MbRecordPeakAnnotation struct {

	// Record format of the annotation blocks
	Header []string `json:"header,omitempty"`

	// Annotation blocks
	Values [][]string `json:"values,omitempty"`
}

// AssertMbRecordPeakAnnotationRequired checks if the required fields are not zero-ed
func AssertMbRecordPeakAnnotationRequired(obj MbRecordPeakAnnotation) error {
	return nil
}

// AssertMbRecordPeakAnnotationConstraints checks if the values respects the defined constraints
func AssertMbRecordPeakAnnotationConstraints(obj MbRecordPeakAnnotation) error {
	return nil
}
