// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




type GetStatus200Response struct {

	Postgres GetStatus200ResponsePostgres `json:"postgres,omitempty"`

	ExportService GetStatus200ResponseExportService `json:"export_service,omitempty"`

	SimilarityService GetStatus200ResponseSimilarityService `json:"similarity_service,omitempty"`
}

// AssertGetStatus200ResponseRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponseRequired(obj GetStatus200Response) error {
	if err := AssertGetStatus200ResponsePostgresRequired(obj.Postgres); err != nil {
		return err
	}
	if err := AssertGetStatus200ResponseExportServiceRequired(obj.ExportService); err != nil {
		return err
	}
	if err := AssertGetStatus200ResponseSimilarityServiceRequired(obj.SimilarityService); err != nil {
		return err
	}
	return nil
}

// AssertGetStatus200ResponseConstraints checks if the values respects the defined constraints
func AssertGetStatus200ResponseConstraints(obj GetStatus200Response) error {
	if err := AssertGetStatus200ResponsePostgresConstraints(obj.Postgres); err != nil {
		return err
	}
	if err := AssertGetStatus200ResponseExportServiceConstraints(obj.ExportService); err != nil {
		return err
	}
	if err := AssertGetStatus200ResponseSimilarityServiceConstraints(obj.SimilarityService); err != nil {
		return err
	}
	return nil
}
