// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// MbRecordCommentsInnerOneOf - A annotated comment
type MbRecordCommentsInnerOneOf struct {

	// The subtag to describe the comment
	Subtag string `json:"subtag,omitempty"`

	// The comment
	Value string `json:"value,omitempty"`
}

// AssertMbRecordCommentsInnerOneOfRequired checks if the required fields are not zero-ed
func AssertMbRecordCommentsInnerOneOfRequired(obj MbRecordCommentsInnerOneOf) error {
	return nil
}

// AssertMbRecordCommentsInnerOneOfConstraints checks if the values respects the defined constraints
func AssertMbRecordCommentsInnerOneOfConstraints(obj MbRecordCommentsInnerOneOf) error {
	return nil
}
