// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server


import (
	"errors"
)



// MbRecordPeakNeutralLossInner - Values for a single neutral loss
type MbRecordPeakNeutralLossInner struct {

	// Difference in mass
	Difference float64 `json:"difference,omitempty"`

	// Peak identifier of the peak in spectrum
	PeakId int32 `json:"peak_id,omitempty"`

	// Precursor mass
	PrecursorMass float64 `json:"precursor_mass,omitempty"`
}

// AssertMbRecordPeakNeutralLossInnerRequired checks if the required fields are not zero-ed
func AssertMbRecordPeakNeutralLossInnerRequired(obj MbRecordPeakNeutralLossInner) error {
	return nil
}

// AssertMbRecordPeakNeutralLossInnerConstraints checks if the values respects the defined constraints
func AssertMbRecordPeakNeutralLossInnerConstraints(obj MbRecordPeakNeutralLossInner) error {
	if obj.Difference < 0 {
		return &ParsingError{Param: "Difference", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.PeakId < 1 {
		return &ParsingError{Param: "PeakId", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.PrecursorMass < 0 {
		return &ParsingError{Param: "PrecursorMass", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
