// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server


import (
	"errors"
)



// MbRecordPeakPeakValuesInner - Values for a single peak
type MbRecordPeakPeakValuesInner struct {

	// Peak identifier
	Id int32 `json:"id,omitempty"`

	// m/z of the peak
	Mz float64 `json:"mz,omitempty"`

	// intensity of the peak
	Intensity float64 `json:"intensity,omitempty"`

	// Relative intensity of the peak
	Rel int32 `json:"rel,omitempty"`
}

// AssertMbRecordPeakPeakValuesInnerRequired checks if the required fields are not zero-ed
func AssertMbRecordPeakPeakValuesInnerRequired(obj MbRecordPeakPeakValuesInner) error {
	return nil
}

// AssertMbRecordPeakPeakValuesInnerConstraints checks if the values respects the defined constraints
func AssertMbRecordPeakPeakValuesInnerConstraints(obj MbRecordPeakPeakValuesInner) error {
	if obj.Id < 1 {
		return &ParsingError{Param: "Id", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Mz < 0 {
		return &ParsingError{Param: "Mz", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Intensity < 0 {
		return &ParsingError{Param: "Intensity", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Rel < 0 {
		return &ParsingError{Param: "Rel", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Rel > 999 {
		return &ParsingError{Param: "Rel", Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
