// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// AuthorsInner - Name of the author or affiliation
type AuthorsInner struct {

	Name string `json:"name"`

	// Marc relator to describe contribution of author or affiliation
	MarcRelator string `json:"marc-relator,omitempty"`
}

// AssertAuthorsInnerRequired checks if the required fields are not zero-ed
func AssertAuthorsInnerRequired(obj AuthorsInner) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAuthorsInnerConstraints checks if the values respects the defined constraints
func AssertAuthorsInnerConstraints(obj AuthorsInner) error {
	return nil
}
