// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




type AcIonMobilityInner struct {

	Subtag string `json:"subtag,omitempty"`

	Value string `json:"value,omitempty"`
}

// AssertAcIonMobilityInnerRequired checks if the required fields are not zero-ed
func AssertAcIonMobilityInnerRequired(obj AcIonMobilityInner) error {
	return nil
}

// AssertAcIonMobilityInnerConstraints checks if the values respects the defined constraints
func AssertAcIonMobilityInnerConstraints(obj AcIonMobilityInner) error {
	return nil
}
