// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// GetStatus200ResponseSimilarityService - The status of the similarity service.
type GetStatus200ResponseSimilarityService struct {

	// The status of the similarity service.
	Status string `json:"status,omitempty"`

	// The error message if the similarity service is not running.
	Error string `json:"error,omitempty"`
}

// AssertGetStatus200ResponseSimilarityServiceRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponseSimilarityServiceRequired(obj GetStatus200ResponseSimilarityService) error {
	return nil
}

// AssertGetStatus200ResponseSimilarityServiceConstraints checks if the values respects the defined constraints
func AssertGetStatus200ResponseSimilarityServiceConstraints(obj GetStatus200ResponseSimilarityService) error {
	return nil
}
