// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server


import (
	"errors"
)



type MetadataCompoundClassInner struct {

	Name string `json:"name,omitempty"`

	Count int32 `json:"count,omitempty"`
}

// AssertMetadataCompoundClassInnerRequired checks if the required fields are not zero-ed
func AssertMetadataCompoundClassInnerRequired(obj MetadataCompoundClassInner) error {
	return nil
}

// AssertMetadataCompoundClassInnerConstraints checks if the values respects the defined constraints
func AssertMetadataCompoundClassInnerConstraints(obj MetadataCompoundClassInner) error {
	if obj.Count < 1 {
		return &ParsingError{Param: "Count", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
