// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




type AcMassSpecSubtagsInner struct {

	Subtag string `json:"subtag,omitempty"`

	Value string `json:"value,omitempty"`
}

// AssertAcMassSpecSubtagsInnerRequired checks if the required fields are not zero-ed
func AssertAcMassSpecSubtagsInnerRequired(obj AcMassSpecSubtagsInner) error {
	return nil
}

// AssertAcMassSpecSubtagsInnerConstraints checks if the values respects the defined constraints
func AssertAcMassSpecSubtagsInnerConstraints(obj AcMassSpecSubtagsInner) error {
	return nil
}
