// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




type AcMassSpec struct {

	MsType string `json:"ms_type,omitempty"`

	IonMode string `json:"ion_mode,omitempty"`

	Subtags []AcMassSpecSubtagsInner `json:"subtags,omitempty"`
}

// AssertAcMassSpecRequired checks if the required fields are not zero-ed
func AssertAcMassSpecRequired(obj AcMassSpec) error {
	for _, el := range obj.Subtags {
		if err := AssertAcMassSpecSubtagsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAcMassSpecConstraints checks if the values respects the defined constraints
func AssertAcMassSpecConstraints(obj AcMassSpec) error {
	for _, el := range obj.Subtags {
		if err := AssertAcMassSpecSubtagsInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
