// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// MsFocusedIonInner - A list of subtag value pairs
type MsFocusedIonInner struct {

	// Subtag describing the value
	Subtag string `json:"subtag,omitempty"`

	// The value for the subtag
	Value string `json:"value,omitempty"`
}

// AssertMsFocusedIonInnerRequired checks if the required fields are not zero-ed
func AssertMsFocusedIonInnerRequired(obj MsFocusedIonInner) error {
	return nil
}

// AssertMsFocusedIonInnerConstraints checks if the values respects the defined constraints
func AssertMsFocusedIonInnerConstraints(obj MsFocusedIonInner) error {
	return nil
}
