// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server


import (
	"errors"
)



// MbRecordPeakNeutralLossInner - Values for a single neutral loss
type MbRecordPeakNeutralLossInner struct {

	// Difference in mass
	Difference float64 `json:"difference,omitempty"`

	// Peak identifier of the first peak
	Peak1Id int32 `json:"peak1_id,omitempty"`

	// Peak identifier of the second peak
	Peak2Id int32 `json:"peak2_id,omitempty"`
}

// AssertMbRecordPeakNeutralLossInnerRequired checks if the required fields are not zero-ed
func AssertMbRecordPeakNeutralLossInnerRequired(obj MbRecordPeakNeutralLossInner) error {
	return nil
}

// AssertMbRecordPeakNeutralLossInnerConstraints checks if the values respects the defined constraints
func AssertMbRecordPeakNeutralLossInnerConstraints(obj MbRecordPeakNeutralLossInner) error {
	if obj.Difference < 0 {
		return &ParsingError{Param: "Difference", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Peak1Id < 1 {
		return &ParsingError{Param: "Peak1Id", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Peak2Id < 1 {
		return &ParsingError{Param: "Peak2Id", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
