// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




type MbRecordMassSpectrometry struct {

	FocusedIon []MsFocusedIonInner `json:"focused_ion,omitempty"`

	DataProcessing []MsDataProcessingInner `json:"data_processing,omitempty"`
}

// AssertMbRecordMassSpectrometryRequired checks if the required fields are not zero-ed
func AssertMbRecordMassSpectrometryRequired(obj MbRecordMassSpectrometry) error {
	for _, el := range obj.FocusedIon {
		if err := AssertMsFocusedIonInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.DataProcessing {
		if err := AssertMsDataProcessingInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertMbRecordMassSpectrometryConstraints checks if the values respects the defined constraints
func AssertMbRecordMassSpectrometryConstraints(obj MbRecordMassSpectrometry) error {
	for _, el := range obj.FocusedIon {
		if err := AssertMsFocusedIonInnerConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.DataProcessing {
		if err := AssertMsDataProcessingInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
