// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// GetStatus200ResponseExportService - The status of the export service.
type GetStatus200ResponseExportService struct {

	// The status of the export service.
	Status string `json:"status,omitempty"`

	// The error message if the export service is not running.
	Error string `json:"error,omitempty"`
}

// AssertGetStatus200ResponseExportServiceRequired checks if the required fields are not zero-ed
func AssertGetStatus200ResponseExportServiceRequired(obj GetStatus200ResponseExportService) error {
	return nil
}

// AssertGetStatus200ResponseExportServiceConstraints checks if the values respects the defined constraints
func AssertGetStatus200ResponseExportServiceConstraints(obj GetStatus200ResponseExportService) error {
	return nil
}
