// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// MsDataProcessingInner - A list of subtag value pairs
type MsDataProcessingInner struct {

	// Subtag describing the value
	Subtag string `json:"subtag,omitempty"`

	// The value for the subtag
	Value string `json:"value,omitempty"`
}

// AssertMsDataProcessingInnerRequired checks if the required fields are not zero-ed
func AssertMsDataProcessingInnerRequired(obj MsDataProcessingInner) error {
	return nil
}

// AssertMsDataProcessingInnerConstraints checks if the values respects the defined constraints
func AssertMsDataProcessingInnerConstraints(obj MsDataProcessingInner) error {
	return nil
}
