// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

package mb3server




// MbRecordDate - Date of creation or last modification of record
type MbRecordDate struct {

	// Date of last update to record
	Updated string `json:"updated,omitempty"`

	// Date of record creation
	Created string `json:"created,omitempty"`

	// Date of last (automatic) modification to record
	Modified string `json:"modified,omitempty"`
}

// AssertMbRecordDateRequired checks if the required fields are not zero-ed
func AssertMbRecordDateRequired(obj MbRecordDate) error {
	return nil
}

// AssertMbRecordDateConstraints checks if the values respects the defined constraints
func AssertMbRecordDateConstraints(obj MbRecordDate) error {
	return nil
}
