// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MassBank3 API
 *
 * The MassBank3 API allows retrieval and filtering of records by chemical or experimental parameters, similarity search on peak lists, and access to individual record details, metadata, service status, and available filter options.
 *
 * API version: 3.0
 */

package mb3server

import (
	"net/http"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/cors"
)

// A Route defines the parameters for an api endpoint
type Route struct {
	Name        string
	Method	    string
	Pattern	    string
	HandlerFunc http.HandlerFunc
}

// Routes is a map of defined api endpoints
type Routes map[string]Route

// Router defines the required methods for retrieving api routes
type Router interface {
	Routes() Routes
	OrderedRoutes() []Route
}

// NewRouter creates a new router for any number of api routers
func NewRouter(routers ...Router) chi.Router {
	router := chi.NewRouter()
	router.Use(Logger)
	router.Use(cors.Handler(cors.Options{}))
	for _, api := range routers {
		for _, route := range api.OrderedRoutes() {
			var handler http.Handler = route.HandlerFunc
			router.Method(route.Method, route.Pattern, handler)
		}
	}

	return router
}
