generatorName: go-server
output: cmd/mb3server
apiDocs: true
modelDocs: true
apiTests: true
modelTests: true
addResponseHeaders: true
featureCORS: true
packageName: mb3server
packageVersion: 0.1.0
router: chi
sourceFolder: src
inputSpec: ../doc/openapi/openapi.yml
templateDir: ./go-server-template
gitUserId: MassBank
gitRepoId: MassBank3/cmd/mb3server
enablePostProcessFile: true
generateAliasAsModel: false