apiVersion: v1
kind: Service
metadata:
  name: massbank3-service
  namespace: massbank3
spec:
  selector:
    app: massbank3-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30002
  type: NodePort