/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/MassBank/MassBank3/pkg/config"
	"log"
	"net/http"
	"strconv"

	mb3server "github.com/MassBank/MassBank3/cmd/mb3server/src"
)

func main() {
	log.Printf("Server started")
	mb3server.ServerConfig = config.GetServerConfig()
	if mb3server.ServerConfig == nil {
		log.Fatal("Could not read config variables")
	}
	DefaultApiService := mb3server.NewDefaultApiService()
	DefaultApiController := mb3server.NewDefaultApiController(DefaultApiService)

	router := mb3server.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":"+strconv.FormatUint(uint64(mb3server.ServerConfig.ServerPort), 10), router))
}
