/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"embed"
	"io/fs"
	"log"
	"net/http"
	"strconv"

	mb3server "github.com/MassBank/MassBank3/cmd/mb3server/src"
	"github.com/MassBank/MassBank3/pkg/config"
	"github.com/go-chi/chi/v5"
)

// Embed the swagger-ui directory

//go:embed swagger-ui
var swaggerContent embed.FS

func main() {
	log.Printf("Server started")
	mb3server.ServerConfig = config.GetServerConfig()
	if mb3server.ServerConfig == nil {
		log.Fatal("Could not read config variables")
	}
	DefaultApiService := mb3server.NewDefaultApiService()
	DefaultApiController := mb3server.NewDefaultAPIController(DefaultApiService)

	router := mb3server.NewRouter(DefaultApiController)

	addSwaggerEndpoint(router)

	log.Fatal(http.ListenAndServe(":"+strconv.FormatUint(uint64(mb3server.ServerConfig.ServerPort), 10), router))

}

func addSwaggerEndpoint(router chi.Router) {
	// Create a subdirectory filesystem for swagger-ui
	fsys, err := fs.Sub(swaggerContent, "swagger-ui")
	if err != nil {
		panic("failed to create sub filesystem: " + err.Error())
	}

	router.Handle("/ui/*", http.StripPrefix("/ui/", http.FileServer(http.FS(fsys))))
}
