/*
 * MassBank3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	mb3server "github.com/MassBank/MassBank3/cmd/mb3server/src"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := mb3server.NewDefaultApiService()
	DefaultApiController := mb3server.NewDefaultApiController(DefaultApiService)

	router := mb3server.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8083", router))
}
