openapi: 3.0.3
info:
  title: "MassBank3 API"
  version: "3.0"
paths:
  /records:
    parameters:
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Contributor"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/InstrumentType"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/MsType"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/IonMode"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Splash"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/CompoundName"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/CompoundClass"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/ExactMass"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/MassTolerance"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Formula"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Peaks"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Intensity"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/NeutralLoss"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/PeakList"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/PeakListThreshold"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/InChI"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/InChIKey"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Substructure"
    get:
      summary: Get records, filtered by the given parameters.
      operationId: getRecords
      responses:
        "200":
          description: "A list of records."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/MBRecord.yaml"

  /records/search:
    parameters:
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Contributor"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/InstrumentType"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/MsType"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/IonMode"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Splash"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/CompoundName"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/CompoundClass"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/ExactMass"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/MassTolerance"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Formula"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Peaks"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Intensity"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/NeutralLoss"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/PeakList"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/PeakListThreshold"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/InChI"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/InChIKey"
      - $ref: "./schemas/FilterParams.yaml#/components/parameters/Substructure"
    get:
      summary: Get a list of records as a search result in a specific format (accession, similarity score)
      operationId: getSearchResults
      responses:
        "200":
          description: "A list of search results."
          content:
            application/json:
              schema:
                $ref: "./schemas/SearchResult.yaml"

  /records/{accession}:
    parameters:
      - name: accession
        in: path
        description: The accession of a record, e.g. MSBNK-AAFC-AC000001.
        required: true
        schema:
          type: string
    get:
      summary: Get a MassBank record.
      operationId: getRecord
      responses:
        "200":
          description: "A MassBank record."
          content:
            application/json:
              schema:
                $ref: "./schemas/MBRecord.yaml"

  /records/{accession}/simple:
    parameters:
      - name: accession
        in: path
        description: The accession of a record, e.g. MSBNK-AAFC-AC000001.
        required: true
        schema:
          type: string
    get:
      summary: Get a MassBank record in with reduced information level (accession, title, peaks, smiles).
      operationId: getSimpleRecord
      responses:
        "200":
          description: "A simple MassBank record (accession, title, peaks, smiles)"
          content:
            application/json:
              schema:
                $ref: "./schemas/MBRecord.yaml"

  /records/count:
    get:
      summary: The number of all records in the database.
      operationId: getCount
      responses:
        "200":
          description: "The record count"
          content:
            application/json:
              schema:
                type: string

  /filter/browse:
    get:
      summary: Get all browse options (contributor, instrument type, ms type, ion mode).
      operationId: getBrowseOptions
      parameters:
        - $ref: "./schemas/FilterParams.yaml#/components/parameters/Contributor"
        - $ref: "./schemas/FilterParams.yaml#/components/parameters/InstrumentType"
        - $ref: "./schemas/FilterParams.yaml#/components/parameters/MsType"
        - $ref: "./schemas/FilterParams.yaml#/components/parameters/IonMode"
      responses:
        "200":
          description: "All browse options"
          content:
            application/json:
              schema:
                $ref: "./schemas/FilterOptions.yaml#/components/schemas/BrowseOptions"

  /metadata:
    get:
      summary: Get the metadata of the database and the current dataset in use. It includes the version, timestamp, git commit hash, unique spectra count (SPLASH), unique compound count (InChI) and compound classes (free text/ChemOnt) with counts.
      operationId: getMetadata
      responses:
        "200":
          description: "Metadata for database and datasets"
          content:
            application/json:
              schema:
                $ref: "./schemas/FilterOptions.yaml#/components/schemas/Metadata"

  /version:
    get:
      summary: Get the current API version.
      operationId: getVersion
      responses:
        "200":
          description: "Version for MassBank API with timestamp of build."
          content:
            application/json:
              schema:
                type: string
                example: MassBank API service 0.1, 2025-01-22T14:20:57+01:00

  /status:
    get:
      summary: Get the status of the attached services (postgres, export service, similarity service).
      operationId: getStatus
      responses:
        "200":
          description: "Status of the attached services."
          content:
            application/json:
              schema:
                type: object
                properties:
                  postgres:
                    description: The status of the postgres database.
                    type: object
                    properties:
                      status:
                        description: The status of the postgres database.
                        type: string
                      error:
                        description: The error message if the postgres database is not running.
                        type: string
                  export_service:
                    description: The status of the export service.
                    type: object
                    properties:
                      status:
                        description: The status of the export service.
                        type: string
                      error:
                        description: The error message if the export service is not running.
                        type: string
                  similarity_service:
                    description: The status of the similarity service.
                    type: object
                    properties:
                      status:
                        description: The status of the similarity service.
                        type: string
                      error:
                        description: The error message if the similarity service is not running.
                        type: string

  /similarity:
    parameters:
      - $ref: "./schemas/SimilaritySearchParams.yaml#/components/parameters/PeakList"
      - $ref: "./schemas/SimilaritySearchParams.yaml#/components/parameters/PeakListThreshold"
      - $ref: "./schemas/SimilaritySearchParams.yaml#/components/parameters/ReferenceSpectraList"
    get:
      summary: Get a list of records with similarity scores.
      operationId: getSimilarity
      responses:
        "200":
          description: "A list of records with similarity scores."
          content:
            application/json:
              schema:
                $ref: "./schemas/SimilaritySearchResult.yaml"
