openapi: 3.0.3
info:
  title: "MassBank3 API"
  version: "3.0"
servers:
  - url: "https://api.server.test/v1"
paths:
  /records:
    parameters:
      - in: query
        name: instrument_type
        description: Filter by a list of instrument type, which will be associated by OR.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/InstrumentType"
        required: false
      - in: query
        description: Filter by SPLASH.
        name: splash
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Splash"
        required: false
      - in: query
        description: Filter by a List of MS types, which are associated by OR. If none is given, all is assumed.
        name: ms_type
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/MSType"
        required: false
      - in: query
        name: ion_mode
        description: Filter by ion mode. If none is given, both is assumed.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/IonMode"
        required: false
      - in: query
        name: compound_name
        description: Filter by compound name
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/CompoundName"
        required: false
      - in: query
        name: exact_mass
        description: Filter by exact mass.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/ExactMass"
      - in: query
        name: mass_tolerance
        description: "Tolerance for mass filters. Default: 0.3"
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/MassTolerance"
      - in: query
        name: formula
        description: Filter by formula.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Formula"
        required: false
      - in: query
        name: peaks
        description: Filter by peaks.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Peaks"
        required: false
      - in: query
        name: intensity
        description: Intensity for peak search, defaults to 100.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Intensity"
        required: false
      - in: query
        name: peak_differences
        description: Filter by peak difference
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Peaks"
        required: false
      - in: query
        name: peak_list
        description: Filter by peak list.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/PeakList"
        required: false
      - in: query
        name: intensity_cutoff
        description: "The Instensity cutoff for Peaklist search. Default: 5"
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/IntensityCutoff"
        required: false
      - in: query
        name: inchi
        description: Filter by InChI
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/InChI"
        required: false
      - in: query
        name: inchi_key
        description: Filter by InChIKey. Complete or Partial
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/InChIKey"
        required: false
      - in: query
        name: contributor
        description: a contributor (institution)
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Contributor"
        required: false
    get:
      summary: Get a list of records
      operationId: getRecords
      responses:
        "200":
          description: "A list of records"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/MBRecord.yaml"
  /records/search:
    parameters:
      - in: query
        name: instrument_type
        description: Filter by a list of instrument type, which will be associated by OR.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/InstrumentType"
        required: false
      - in: query
        description: Filter by SPLASH.
        name: splash
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Splash"
        required: false
      - in: query
        description: Filter by a List of MS types, which are associated by OR. If none is given, all is assumed.
        name: ms_type
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/MSType"
        required: false
      - in: query
        name: ion_mode
        description: Filter by ion mode. If none is given, both is assumed.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/IonMode"
        required: false
      - in: query
        name: compound_name
        description: Filter by compound name
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/CompoundName"
        required: false
      - in: query
        name: exact_mass
        description: Filter by exact mass.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/ExactMass"
      - in: query
        name: mass_tolerance
        description: "Tolerance for mass filters. Default: 0.3"
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/MassTolerance"
      - in: query
        name: formula
        description: Filter by formula.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Formula"
        required: false
      - in: query
        name: peaks
        description: Filter by peaks.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Peaks"
        required: false
      - in: query
        name: intensity
        description: Intensity for peak search, defaults to 100.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Intensity"
        required: false
      - in: query
        name: peak_differences
        description: Filter by peak difference
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Peaks"
        required: false
      - in: query
        name: peak_list
        description: Filter by peak list.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/PeakList"
        required: false
      - in: query
        name: intensity_cutoff
        description: "The Instensity cutoff for Peaklist search. Default: 5"
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/IntensityCutoff"
        required: false
      - in: query
        name: inchi
        description: Filter by InChI
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/InChI"
        required: false
      - in: query
        name: inchi_key
        description: Filter by InChIKey. Complete or Partial
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/InChIKey"
        required: false
      - in: query
        name: contributor
        description: a contributor (institution)
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Contributor"
        required: false
    get:
      summary: Get a list of records as a search result in a specific format (accession, title, peaks, smiles, similarity search result)
      operationId: getSearchRecords
      responses:
        "200":
          description: "A list of simple records as a search result"
          content:
            application/json:
              schema:
                $ref: "./schemas/SearchResult.yaml"

  /records/{accession}:
    parameters:
      - name: accession
        in: path
        description: The accession id of the record
        required: true
        schema:
          type: string
    get:
      summary: Get a MassBank record
      operationId: getRecord
      responses:
        "200":
          description: "A MassBank record"
          content:
            application/json:
              schema:
                $ref: "./schemas/MBRecord.yaml"
  /records/{accession}/simple:
    parameters:
      - name: accession
        in: path
        description: The accession id of the record
        required: true
        schema:
          type: string
    get:
      summary: Get a MassBank record in simple format (accession, title, peaks, smiles)
      operationId: getSimpleRecord
      responses:
        "200":
          description: "A simple MassBank record (accession, title, peaks, smiles)"
          content:
            application/json:
              schema:
                $ref: "./schemas/MBRecord.yaml"
  /records/count:
    get:
      summary: The number of all records
      operationId: getCount
      responses:
        "200":
          description: "The record count"
          content:
            application/json:
              schema:
                type: string
  /filter/browse:
    get:
      summary: get browse options
      operationId: getBrowseOptions
      parameters:
        - in: query
          name: instrument_type
          description: Filter by a list of instrument type, which will be associated by OR.
          schema:
            $ref: "./schemas/FilterSchemas.yaml#/components/schemas/InstrumentType"
          required: false
        - in: query
          description: Filter by a List of MS types, which are associated by OR. If none is given, all is assumed.
          name: ms_type
          schema:
            $ref: "./schemas/FilterSchemas.yaml#/components/schemas/MSType"
          required: false
        - in: query
          name: ion_mode
          description: Filter by ion mode. If none is given, both is assumed.
          schema:
            $ref: "./schemas/FilterSchemas.yaml#/components/schemas/IonMode"
          required: false
        - in: query
          name: contributor
          description: a contributor (institution)
          schema:
            $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Contributor"
          required: false
      responses:
        "200":
          description: "All browse options"
          content:
            application/json:
              schema:
                $ref: "./schemas/FilterOptions.yaml#/components/schemas/BrowseOptions"
  /metadata:
    get:
      summary: get massbank metadata
      operationId: getMetadata
      responses:
        "200":
          description: "Metadata for database and datasets"
          content:
            application/json:
              schema:
                $ref: "./schemas/FilterOptions.yaml#/components/schemas/Metadata"

  /similarity:
    parameters:
      - in: query
        name: peak_list
        description: Filter by peak list.
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/PeakList"
        required: true
      - in: query
        name: reference_spectra_list
        description: Filter by reference spectra list.
        schema:
          type: array
          items:
            type: string
          example:
            - MSBNK-IPB_Halle-PB001341
            - MSBNK-IPB_Halle-PB006202
            - MSBNK-IPB_Halle-PB006203
            - MSBNK-IPB_Halle-PB001342
            - MSBNK-IPB_Halle-PB001343
        required: false
      - in: query
        name: limit
        description: "Maximum number of results."
        schema:
          $ref: "./schemas/FilterSchemas.yaml#/components/schemas/Limit"
        required: false
    get:
      summary: Get a list of records with similarity scores
      operationId: getSimilarity
      responses:
        "200":
          description: "A list of similar records"
          content:
            application/json:
              schema:
                $ref: "./schemas/SimilaritySearchResult.yaml"
