name: Create Docker Container

on:
  release:
    types: [released]

jobs:
  build-and-push-images:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile-dbtool
            image: quay.io/massbank/massbank-dbtool
            context: .
          - dockerfile: ./Dockerfile-server
            image: quay.io/massbank/massbank-api
            context: .
          - dockerfile: ./web-frontend/Dockerfile-frontend
            image: quay.io/massbank/massbank-frontend
            context: ./web-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Output tags
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
