name: Create Docker Container

on:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - "v*"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile-dbtool
            image: quay.io/massbank/massbank-dbtool
            context: .
          - dockerfile: ./Dockerfile-server
            image: quay.io/massbank/massbank-api
            context: .
          - dockerfile: ./web-frontend/Dockerfile-frontend
            image: quay.io/massbank/massbank-frontend
            context: ./web-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            # tag event
            type=ref,event=tag
            # set latest tag for main branch and tags
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
            # set dev tag for dev branch, but exclude ipbhalle/postgres
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}