
name: go-test

on:
  push:
    branches: [ "*"]
  pull_request:
    branches: [ "*" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        mongodb-version: ['5.0', '6.0']
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: mbtestuser
        mongodb-password: mbtestpwd
        mongodb-db: mbtestdb

    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Run all go tests
      run: go test ./... -v -covermode=count -coverprofile=coverage.out
      env:
        MONGODB_HOST: localhost

    -